package tacit.mcp

import tacit.core.*
import Context.*
import tacit.executor.{CodeRecorder, ExecutionResult, ManagedRepl, ScalaExecutor, SessionManager}

import io.circe.*
import io.circe.syntax.*

/** Build info loaded from version.properties (generated by sbt). */
private object BuildInfo:
  private val props = java.util.Properties()
  locally:
    val stream = classOf[McpServer].getResourceAsStream("/version.properties")
    if stream != null then
      try props.load(stream)
      finally stream.close()
  val version: String = Option(props.getProperty("version")).getOrElse("0.0.0-unknown")
  val name: String = Option(props.getProperty("name")).getOrElse("TACIT")

/** API reference displayed by show_interface. Mirrors the API surface that
  * ManagedRepl.libraryPreamble actually imports: core docs are included when
  * no plugin is loaded or every plugin uses `extend-core`, and omitted when
  * any plugin uses `replace-core`.
  */
private[tacit] def computeInterfaceReference(using Context): String =
  val preamble =
    """|IMPORTANT: You must only use the provided interface below to interact with the system.
       |Do not use Java/Scala standard library APIs (java.io, java.nio, scala.io, sys.process, java.net, etc.) to access files, run processes, or make network requests directly.
       |All system interactions must go through the capability-scoped API so that access is properly sandboxed and auditable.
       |
       |The interface is pre-loaded and available in all code executions.
       |
       |""".stripMargin

  val plugins = ctx.plugins
  if plugins.isEmpty then preamble + coreInterfaceReference
  else
    val includeCore = plugins.forall(_.manifest.apiMode == ApiMode.ExtendCore)
    val coreDocs    = Option.when(includeCore)(coreInterfaceReference).toList
    val pluginDocs  = plugins.map: p =>
      s"## ${p.manifest.name}\n\n${p.apiDocs}"
    preamble + pluginSummary(plugins) + "# Available API\n\n" +
      (coreDocs ++ pluginDocs).mkString("\n\n---\n\n")

/** Core API reference, bundled inside the library JAR as `Interface.scala.txt`
  * (it lives with the library it documents, not on the server's classpath). */
private def coreInterfaceReference(using Context): String =
  ManagedRepl.readLibraryResource("Interface.scala.txt") match
    case Some(content) => "```scala\n" + content + "\n```"
    case None =>
      System.err.println("[TACIT MCP] WARNING: Interface.scala resource not found in library JAR")
      "(Interface.scala source not found in library JAR)"

private def pluginSummary(plugins: List[LoadedPlugin]): String =
  val rows = plugins.map: p =>
    val m = p.manifest
    val domain      = m.domain.fold("")(d => s"\nDomain: $d")
    val description = m.description.fold("")(d => s"\n$d")
    s"""|## ${m.name} ${m.version}
        |ID: ${m.id}
        |Mode: ${renderApiMode(m.apiMode)}$domain$description
        |""".stripMargin
  "# Loaded TACIT plugins\n\n" + rows.mkString("\n") + "\n\n"

private def renderApiMode(mode: ApiMode): String = mode match
  case ApiMode.ExtendCore  => "extend-core"
  case ApiMode.ReplaceCore => "replace-core"

/** MCP Server implementation for Scala code execution */
class McpServer(using Context):
  private val ProtocolVersion = "2025-11-25"

  private val sessionManager = SessionManager()

  private inline def recorder: Option[CodeRecorder] = ctx.recorder
  private inline def sessionEnabled: Boolean = ctx.config.sessionEnabled

  /** Handle a JSON-RPC request and return a response */
  def handleRequest(request: JsonRpcRequest): Option[JsonRpcResponse] =
    request.method match
      case "initialize" =>
        handleInitialize(request)
      case "notifications/initialized" | "initialized" =>
        // Notification, no response needed (accept both for backward compat)
        None
      case "tools/list" =>
        handleToolsList(request)
      case "tools/call" =>
        handleToolsCall(request)
      case "ping" =>
        Some(JsonRpcResponse.success(request.id, Json.obj()))
      case "notifications/cancelled" =>
        // Notification, no response needed
        None
      case other if other.startsWith("notifications/") =>
        // All notifications - no response needed
        None
      case other =>
        Some(JsonRpcResponse.error(
          request.id,
          JsonRpcError.MethodNotFound,
          s"Method not found: $other"
        ))
  
  private def handleInitialize(request: JsonRpcRequest): Option[JsonRpcResponse] =
    val result = InitializeResult(
      protocolVersion = ProtocolVersion,
      capabilities = ServerCapabilities(
        tools = Some(ToolsCapability(listChanged = Some(true)))
      ),
      serverInfo = ServerInfo(
        name = s"${BuildInfo.name} MCP",
        version = BuildInfo.version
      )
    )
    Some(JsonRpcResponse.success(request.id, result.asJson))
  
  private def handleToolsList(request: JsonRpcRequest): Option[JsonRpcResponse] =
    val tools = if sessionEnabled then Tools.all
                else Tools.all.filterNot(t => Tools.isSessionTool(t.name))
    val result = ToolsListResult(tools)
    Some(JsonRpcResponse.success(request.id, result.asJson))
  
  private def handleToolsCall(request: JsonRpcRequest): Option[JsonRpcResponse] =
    val result = for
      params <- request.params.toRight("Missing params")
      callParams <- params.as[CallToolParams].left.map(_.message)
      toolResult <- callTool(callParams.name, callParams.arguments)
    yield toolResult
    
    result match
      case Right(toolResult) =>
        Some(JsonRpcResponse.success(request.id, toolResult.asJson))
      case Left(error) =>
        Some(JsonRpcResponse.error(
          request.id,
          JsonRpcError.InvalidParams,
          error
        ))
  
  private def callTool(name: String, arguments: Option[Json]): Either[String, CallToolResult] =
    if !sessionEnabled && Tools.isSessionTool(name) then
      Left(s"Session tools are disabled. Use execute_scala for stateless execution.")
    else name match
      case "execute_scala" =>
        executeScala(arguments)
      case "create_repl_session" =>
        createReplSession()
      case "delete_repl_session" =>
        deleteReplSession(arguments)
      case "execute_in_session" =>
        executeInSession(arguments)
      case "list_sessions" =>
        listSessions()
      case "show_interface" =>
        showInterface()
      case other =>
        Left(s"Unknown tool: $other")
  
  private def executeScala(arguments: Option[Json]): Either[String, CallToolResult] =
    for
      args <- arguments.toRight("Missing arguments")
      code <- args.hcursor.get[String]("code").left.map(_.message)
    yield
      val result = ScalaExecutor.execute(code)
      recorder.foreach(_.record(code, "stateless", result))
      formatExecutionResult(result)
  
  private def createReplSession(): Either[String, CallToolResult] =
    val sessionId = sessionManager.createSession()
    Right(CallToolResult(
      content = List(TextContent(s"Created REPL session: $sessionId"))
    ))
  
  private def deleteReplSession(arguments: Option[Json]): Either[String, CallToolResult] =
    for
      args <- arguments.toRight("Missing arguments")
      sessionId <- args.hcursor.get[String]("session_id").left.map(_.message)
    yield
      if sessionManager.deleteSession(sessionId) then
        CallToolResult(content = List(TextContent(s"Deleted session: $sessionId")))
      else
        CallToolResult(
          content = List(TextContent(s"Session not found: $sessionId")),
          isError = Some(true)
        )
  
  private def executeInSession(arguments: Option[Json]): Either[String, CallToolResult] =
    for
      args <- arguments.toRight("Missing arguments")
      sessionId <- args.hcursor.get[String]("session_id").left.map(_.message)
      code <- args.hcursor.get[String]("code").left.map(_.message)
    yield
      val result = sessionManager.executeInSession(sessionId, code)
      recorder.foreach(_.record(code, sessionId, result))
      formatExecutionResult(result)
  
  private def listSessions(): Either[String, CallToolResult] =
    val sessions = sessionManager.listSessions()
    val text = if sessions.isEmpty then
      "No active sessions"
    else
      s"Active sessions:\n${sessions.mkString("\n")}"
    Right(CallToolResult(content = List(TextContent(text))))
  
  private def showInterface(): Either[String, CallToolResult] =
    Right(CallToolResult(content = List(TextContent(computeInterfaceReference))))

  private def formatExecutionResult(result: ExecutionResult): CallToolResult =
    val output = result.error match
      case Some(err) if result.output.nonEmpty =>
        s"${result.output}\n\nError: $err"
      case Some(err) =>
        s"Error: $err"
      case None =>
        if result.output.isEmpty then "(no output)" else result.output
    
    CallToolResult(
      content = List(TextContent(output)),
      isError = if result.success then None else Some(true)
    )
